<?php

declare(strict_types=1);

use App\Enums\OrgRole;
use App\Enums\SourceState;
use App\Models\AuditLog;
use App\Models\KnowledgeSource;
use App\Models\Organization;
use App\Models\SourceItem;
use App\Models\User;
use App\Services\Audit\AuditLogger;
use App\Services\Sources\Upload\UploadLimits;
use App\Support\Kb\ObjectKey;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Storage;
use Tests\Support\SpaSession;

/*
|--------------------------------------------------------------------------
| POST .../sources with files — the ENDPOINT's half of the upload intake
|--------------------------------------------------------------------------
|
| The gate's own steps and their ORDER are tests/Unit/UploadIntakeGateTest.php, which asserts the
| `reason` token for every branch with no container and no database. What is asserted HERE is
| everything the gate cannot see on its own:
|
|   * the STORAGE KEY, built by ObjectKey and checked against the CREATED ROW'S OWN ids rather than
|     against a string this file wrote down — a test that re-derives the key from constants passes
|     against a service that builds a key for the wrong organization;
|   * the two AUDIT OPERATIONS, `source.upload.accepted` per file and `source.upload.rejected` per
|     refusal, including the ordering property seen from the audit table, which is where an operator
|     actually reads it;
|   * ALL-OR-NOTHING: a batch with one bad file leaves no source, no item and no object;
|   * TENANCY: two organizations uploading byte-identical content get two objects at two prefixes.
|
| EVERY FIXTURE IS TWO ORGANIZATIONS, even where the assertion looks single-tenant — a
| one-organization fixture passes every assertion below against code with the tenant scope deleted.
|
| `Storage::fake('s3')` REMOVES THE NETWORK AND NOT THE PROPERTY. The key is still generated by
| ObjectKey, and `source_items_storage_key_is_tenant_scoped` still compares it against the ROW'S OWN
| `organization_id` on the INSERT — so a key built for another tenant is refused by PostgreSQL in
| this suite exactly as it would be in production. What the fake does NOT exercise is
| `MultipartUploader`: a faked disk is a local one with no S3 client, so `SourceObjectWriter` takes
| its `writeStream()` branch here. That branch is documented at the class and asserted by
| tests/Arch/StringLevelDoctrineTest.php, which is what keeps `file_get_contents` out of the file.
|
| `Queue::fake()` because create dispatches `SubmitIngestionJob`, whose handler calls the AI service;
| the suite's QUEUE_CONNECTION is `sync`, so an unfaked dispatch would run it inline and turn every
| 201 into a 503 against an ai-api that is not there.
*/

beforeEach(function (): void {
    SpaSession::isolateRateLimits(currentTest());
    Storage::fake('s3');
    Queue::fake();
});

/**
 * Two organizations, an owner in each, and nothing else.
 *
 * A HELPER OF THIS FILE'S OWN, with a name of its own: Pest declares test-file helpers at FILE
 * SCOPE, so a name another test file already uses is a redeclaration fatal in a full run — and only
 * in a full run, which is the worst possible time to discover it.
 *
 * @return array{orgA: Organization, orgB: Organization, ownerA: User, ownerB: User}
 */
function sourceUploadFixture(): array
{
    $orgA = Organization::factory()->create(['name' => 'Upload Org ALPHA', 'slug' => 'upload-alpha']);
    $orgB = Organization::factory()->create(['name' => 'Upload Org BRAVO', 'slug' => 'upload-bravo']);

    return [
        'orgA' => $orgA,
        'orgB' => $orgB,
        'ownerA' => User::factory()->recycle($orgA)->orgRole(OrgRole::Owner)
            ->create(['email' => SpaSession::uniqueEmail('upload-owner-alpha')]),
        'ownerB' => User::factory()->recycle($orgB)->orgRole(OrgRole::Owner)
            ->create(['email' => SpaSession::uniqueEmail('upload-owner-bravo')]),
    ];
}

/** Real PDF bytes — libmagic reads them as `application/pdf`. */
function sourceUploadPdfBytes(): string
{
    return "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        ."trailer\n<< /Root 1 0 R >>\n%%EOF\n";
}

/** A DOS/PE header — `application/x-dosexec`, which is on no allow-list. */
function sourceUploadExecutableBytes(): string
{
    return "MZ\x90\x00\x03\x00\x00\x00\x04\x00\x00\x00\xFF\xFF\x00\x00"
        .str_repeat("\x00", 48)."\x80\x00\x00\x00".str_repeat("\x00", 64)."PE\x00\x00L\x01";
}

function sourceUploadFile(string $name, string $bytes): UploadedFile
{
    return UploadedFile::fake()->createWithContent($name, $bytes);
}

// ── the accepted path ────────────────────────────────────────────────────────────────────────────

it('stores each accepted file at an ObjectKey-built, tenant-scoped key and gives it its own item', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    $pdf = sourceUploadPdfBytes();
    $html = "<!DOCTYPE html>\n<html><head><title>Policy</title></head><body><p>30 days.</p></body></html>\n";

    $response = currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        [
            'type' => 'file',
            'name' => 'Onboarding pack',
            'files' => [
                sourceUploadFile('Employee Handbook.pdf', $pdf),
                sourceUploadFile('policy.html', $html),
            ],
        ],
        spaHeaders(),
    );

    $response->assertCreated()
        ->assertJsonPath('data.type', 'file')
        // CREATION AND SUBMISSION ARE ONE ACT, exactly as for a paste: a caller who has just handed
        // over ten megabytes has plainly submitted them.
        ->assertJsonPath('data.status', SourceState::Queued->value)
        ->assertJsonPath('data.origin_url', null);

    $sourceId = (string) $response->json('data.id');

    /** @var list<SourceItem> $items */
    $items = SourceItem::query()->withoutGlobalScopes()
        ->where('source_id', '=', $sourceId)->orderBy('id')->get()->all();

    expect($items)->toHaveCount(2);

    // ONE ITEM PER FILE, IN REQUEST ORDER. ULIDs sort by creation, `itemsFor()` reads them back
    // ordered by id, and `IngestionSubmission::fingerprint()` hashes them in that order — so a
    // reordering here would change the idempotency key of an unchanged submission.
    expect($items[0]->display_name)->toBe('Employee Handbook.pdf');
    expect($items[1]->display_name)->toBe('policy.html');

    foreach ([[$items[0], $pdf, 'application/pdf'], [$items[1], $html, 'text/html']] as [$item, $bytes, $mime]) {
        // THE KEY IS RE-DERIVED FROM THE ROW'S OWN IDS, not from a literal this test wrote. A key
        // built for another organization would still match a hardcoded string if the string were
        // wrong in the same way; it cannot match `$item->organization_id`.
        expect($item->storage_key)->toBe(
            ObjectKey::originalUpload($item->organization_id, $item->source_id, (string) $item->content_hash),
        );
        expect($item->organization_id)->toBe($f['orgA']->id);
        expect($item->storage_key)->toStartWith("org/{$f['orgA']->id}/sources/{$sourceId}/original/");

        // THE CANONICAL KEY OF AN UPLOAD IS ITS OBJECT KEY (the `source_items` migration says so),
        // which is what makes `source_items_org_source_canonical` refuse the same object twice.
        expect($item->canonical_key)->toBe($item->storage_key);

        // SNIFFED FROM CONTENT. The multipart part carried a browser-guessed `Content-Type` that
        // nothing on this path read.
        expect($item->mime)->toBe($mime);
        expect($item->byte_size)->toBe(strlen($bytes));
        // INTEGRITY IS OUR SHA-256 IN POSTGRESQL, NEVER THE ETAG (`seaweedfs-s3` NN5).
        expect($item->content_hash)->toBe(hash('sha256', $bytes));

        // The bytes really are there, and they really are the bytes.
        Storage::disk('s3')->assertExists((string) $item->storage_key);
        expect(Storage::disk('s3')->get((string) $item->storage_key))->toBe($bytes);

        // AN UPLOAD HAS NO ORIGIN TO LINK BACK TO. Putting the object key in `url` would fail
        // `source_items_url_scheme` besides.
        expect($item->url)->toBeNull();
    }
});

it('writes one source.upload.accepted row per file, naming the item and the sniffed type', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    $bytes = sourceUploadPdfBytes();

    $response = currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        ['type' => 'file', 'name' => 'Handbook', 'files' => [sourceUploadFile('Handbook.pdf', $bytes)]],
        spaHeaders(),
    );

    $response->assertCreated();

    $sourceId = (string) $response->json('data.id');
    $item = SourceItem::query()->withoutGlobalScopes()->where('source_id', '=', $sourceId)->sole();

    $row = AuditLog::query()->where('operation', '=', AuditLogger::SOURCE_UPLOAD_ACCEPTED)->sole();

    // `subject_id` IS THE SOURCE, because that is what was authorized and what a reader searches by;
    // the item is in `details`, where it survives the source being hard-deleted.
    expect($row->subject_id)->toBe($sourceId);
    expect($row->actor_id)->toBe($f['ownerA']->id);
    expect($row->organization_id)->toBe($f['orgA']->id);
    expect($row->details['source_item_id'] ?? null)->toBe($item->id);
    expect($row->details['display_name'] ?? null)->toBe('Handbook.pdf');
    expect($row->details['mime'] ?? null)->toBe('application/pdf');
    expect($row->details['byte_size'] ?? null)->toBe(strlen($bytes));
    expect($row->details['content_hash'] ?? null)->toBe(hash('sha256', $bytes));
    expect($row->details['storage_key'] ?? null)->toBe($item->storage_key);

    // A GENERATED PATH AND NEVER THE UPLOADED FILENAME. The audit table is append-only and
    // long-lived; a key naming an object outside this organization's prefix would outlive the
    // mistake that made it.
    expect($row->details['storage_key'] ?? '')->toStartWith("org/{$f['orgA']->id}/");
});

it('submits every uploaded item on one job, so a batch is one ingestion run', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    $response = currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        [
            'type' => 'file',
            'name' => 'Pack',
            'files' => [
                sourceUploadFile('one.pdf', sourceUploadPdfBytes()),
                sourceUploadFile('two.pdf', sourceUploadPdfBytes()."% two\n"),
            ],
        ],
        spaHeaders(),
    );

    $response->assertCreated();

    $items = SourceItem::query()->withoutGlobalScopes()
        ->where('source_id', '=', (string) $response->json('data.id'))->get();

    // ONE JOB ID ACROSS THE BATCH, and the sequence reset with it. A job id with no reset, or a
    // reset with no job id, is half the callback guard.
    expect($items->pluck('current_job_id')->unique()->values()->all())->toHaveCount(1);
    expect($items->pluck('progress_sequence')->unique()->all())->toBe([0]);
});

// ── the refused path, which is where the ordering shows up in the audit table ────────────────────

it('creates nothing at all when any file in the batch is refused', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    $response = currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        [
            'type' => 'file',
            'name' => 'Onboarding pack',
            'files' => [
                sourceUploadFile('Handbook.pdf', sourceUploadPdfBytes()),
                sourceUploadFile('payload.exe', sourceUploadExecutableBytes()),
            ],
        ],
        spaHeaders(),
    );

    // KEYED ON THE PART INDEX THE CLIENT SENT, so the console renders the error against the row the
    // operator can see rather than as a banner about "the upload".
    $response->assertStatus(422)->assertJsonStructure(['errors' => ['files.1']]);
    expect($response->json('errors'))->not->toHaveKey('files.0');

    // ALL-OR-NOTHING. A batch that stored the good file and refused the bad one would leave an
    // orphan object under a source id that never became a row — outside every prefix the phase-2
    // purge visits, which is the shape ObjectKey's docblock calls "certified clean while it
    // survives".
    expect(KnowledgeSource::query()->withoutGlobalScopes()->count())->toBe(0);
    expect(SourceItem::query()->withoutGlobalScopes()->count())->toBe(0);
    expect(Storage::disk('s3')->allFiles())->toBe([]);
});

it('records the refusal with the token of the step that answered, which is the ORDER in the audit table', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    // FAILS BOTH STEP 2 AND STEP 3: `.exe` is on no allow-list and `application/x-dosexec` is on no
    // allow-list. Only the order decides which token is written.
    //
    // MUTATION CHECK: swap `assertExtensionIsAllowed()` and `assertMimeIsAllowed()` in
    // UploadIntake::admit() and this row reads `mime_sniff`. The request is still a 422 either way,
    // which is exactly why the assertion is on the token and not on the status.
    currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        ['type' => 'file', 'name' => 'Pack', 'files' => [sourceUploadFile('payload.exe', sourceUploadExecutableBytes())]],
        spaHeaders(),
    )->assertStatus(422);

    $row = AuditLog::query()->where('operation', '=', AuditLogger::SOURCE_UPLOAD_REJECTED)->sole();

    expect($row->details['reason'] ?? null)->toBe('extension');
    expect($row->details['display_name'] ?? null)->toBe('payload.exe');
    // ABSENT, NOT NULL-AND-PRESENT. A refusal before the sniff has no MIME to report, and
    // `AuditLogger::sanitize()` skips a null silently — so the key's absence is what says
    // "we never looked", which is the same ordering fact the token carries.
    expect($row->details)->not->toHaveKey('mime');
    expect($row->actor_id)->toBe($f['ownerA']->id);
    expect($row->organization_id)->toBe($f['orgA']->id);

    // NO SUBJECT: there is no row to point at, which is what a rejection means.
    expect($row->subject_id)->toBeNull();
    expect($row->subject_type)->toBeNull();

    // AND IT IS A FAILURE ROW. `outcome` is derived from the operation rather than passed in, so a
    // rejection can never be recorded as a success.
    expect($row->outcome)->toBe(AuditLogger::OUTCOME_FAILURE);
});

it('writes one rejection row per refused file rather than one per request', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        [
            'type' => 'file',
            'name' => 'Pack',
            'files' => [
                sourceUploadFile('payload.exe', sourceUploadExecutableBytes()),
                // A polyglot: allow-listed extension, allow-listed sniffed type, and they disagree.
                sourceUploadFile('diagram.png', sourceUploadPdfBytes()),
            ],
        ],
        spaHeaders(),
    )->assertStatus(422)->assertJsonStructure(['errors' => ['files.0', 'files.1']]);

    $reasons = AuditLog::query()
        ->where('operation', '=', AuditLogger::SOURCE_UPLOAD_REJECTED)
        ->orderBy('id')
        ->get()
        ->map(static fn (AuditLog $row): mixed => $row->details['reason'] ?? null)
        ->all();

    // A caller grinding at the gate leaves a row per attempt, which is the whole reason the pair is
    // two operations rather than one: without them, refusals are invisible because nothing was
    // written anywhere else.
    expect($reasons)->toBe(['extension', 'mime_mismatch']);
});

// ── tenancy ──────────────────────────────────────────────────────────────────────────────────────

it('gives two organizations uploading identical bytes two objects under two prefixes', function (): void {
    $f = sourceUploadFixture();

    $bytes = sourceUploadPdfBytes();

    /**
     * Upload the same bytes as one organization's owner and return the key they landed at.
     */
    $upload = static function (Organization $organization, User $owner) use ($bytes): string {
        SpaSession::freshProcess();
        SpaSession::establish(currentTest(), $owner);

        $response = currentTest()->post(
            "/api/v1/organizations/{$organization->id}/sources",
            ['type' => 'file', 'name' => 'Price list', 'files' => [sourceUploadFile('prices.pdf', $bytes)]],
            spaHeaders(),
        );

        $response->assertCreated();

        return (string) SourceItem::query()->withoutGlobalScopes()
            ->where('source_id', '=', (string) $response->json('data.id'))->sole()->storage_key;
    };

    $keys = [
        'orgA' => $upload($f['orgA'], $f['ownerA']),
        'orgB' => $upload($f['orgB'], $f['ownerB']),
    ];

    // CONTENT-ADDRESSING NEVER CROSSES AN ORGANIZATION. A shared `objects/{sha256}` root would make
    // one price list one object — an existence oracle, and a deletion hazard where removing one
    // tenant's source takes another tenant's live file.
    expect($keys['orgA'])->not->toBe($keys['orgB']);
    expect($keys['orgA'])->toStartWith("org/{$f['orgA']->id}/");
    expect($keys['orgB'])->toStartWith("org/{$f['orgB']->id}/");

    // THE POSITIVE CONTROL: both objects really are there. Without it this passes against a service
    // that stored neither.
    Storage::disk('s3')->assertExists($keys['orgA']);
    Storage::disk('s3')->assertExists($keys['orgB']);
});

// ── the shape rules the FormRequest owns, asserted through the endpoint that enforces them ───────

it('refuses files alongside a url source, and a file source with no files', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        [
            'type' => 'url',
            'name' => 'Docs site',
            'origin_url' => 'https://example.com/docs',
            'files' => [sourceUploadFile('Handbook.pdf', sourceUploadPdfBytes())],
        ],
        spaHeaders(),
    )->assertStatus(422)->assertJsonStructure(['errors' => ['files']]);

    currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        ['type' => 'file', 'name' => 'Empty'],
        spaHeaders(),
    )->assertStatus(422)->assertJsonStructure(['errors' => ['files']]);

    expect(KnowledgeSource::query()->withoutGlobalScopes()->count())->toBe(0);
});

it('refuses a batch larger than the published cap, without opening a single file', function (): void {
    $f = sourceUploadFixture();

    SpaSession::establish(currentTest(), $f['ownerA']);

    $files = [];

    for ($i = 0; $i <= UploadLimits::maxBatch(); $i++) {
        $files[] = sourceUploadFile("doc{$i}.pdf", sourceUploadPdfBytes()."% {$i}\n");
    }

    currentTest()->post(
        "/api/v1/organizations/{$f['orgA']->id}/sources",
        ['type' => 'file', 'name' => 'Too many', 'files' => $files],
        spaHeaders(),
    )->assertStatus(422)->assertJsonStructure(['errors' => ['files']]);

    // NOTHING WAS SCREENED, so there is no rejection row: the batch cap is the FormRequest's and it
    // runs before the intake. Recording eleven `source.upload.rejected` rows for one over-long batch
    // would bury the rows that mean somebody is probing the gate.
    expect(AuditLog::query()->where('operation', '=', AuditLogger::SOURCE_UPLOAD_REJECTED)->count())->toBe(0);
    expect(Storage::disk('s3')->allFiles())->toBe([]);
});
