<?php

declare(strict_types=1);

namespace App\Models;

use App\Support\Tenancy\OrgOwned;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One object-storage key a request is ABOUT TO WRITE, and the only record that names the bytes if
 * the request never commits a row for them. Security finding S3; see the migration for the defect.
 *
 * ── THERE IS NO `#[ScopedBy(OrganizationScope::class)]`, AND THAT IS A DECISION ───────────────
 *
 * Every other org-owned model in this application carries it. This one must not, and the reason is
 * the scope's own failure direction rather than a convenience: `OrganizationScope` FAILS CLOSED —
 * with no bound tenant context it applies `whereRaw('1 = 0')`. The only reader of this table that
 * matters is `kb:sweep-orphan-objects`, a cross-tenant console command with no request and no
 * session, so a scoped model would make the sweep read ZERO ROWS, every hour, forever, while
 * exiting 0 and reporting "nothing to collect" — the sweep silently ceasing to exist, which is the
 * precise state finding S3 describes.
 *
 * `OrganizationUser` and `OrganizationInvitation` are exempt for the mirror-image reason (they are
 * read BEFORE a context exists), and `tests/Arch/DoctrineTest.php`'s pending reflection rule
 * already says such a list has to carry each model's reason inline. This is that reason.
 *
 * WHAT REPLACES THE SCOPE IS NOT NOTHING. Every request-path query goes through
 * `EloquentPendingSourceObjectRepository`, whose every method takes `$organizationId` as a required
 * positional argument and puts it in the predicate; the sweep binds a real `TenantContext` per row
 * before it touches anything else, so the SCOPED tables it consults (`source_items`) are filtered
 * normally; and the database refuses a row whose `storage_key` is outside its own organization's
 * prefix. The table also holds no tenant content — an organization id, a source id it may never
 * own, and a key this application generated — so the thing a scope protects is not here.
 *
 * ── IT HAS A `created_at` AND NO `updated_at` ────────────────────────────────────────────────
 *
 * A reservation is never updated. It is written, and then it is either released (the request
 * committed) or collected (it did not). `UPDATED_AT = null` tells Eloquent so; without it every
 * `save()` writes a column that does not exist.
 *
 * @property string $id
 * @property string $organization_id
 * @property string $source_id
 * @property string $storage_key
 * @property \Illuminate\Support\Carbon $created_at
 */
final class PendingSourceObject extends Model implements OrgOwned
{
    /** @use HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<self>> */
    use HasFactory;

    use HasUlids;

    /**
     * A reservation is written once and never modified. See the docblock: an `updated_at` Eloquent
     * believes in and PostgreSQL does not have is an SQLSTATE 42703 on every write.
     */
    public const UPDATED_AT = null;

    protected $table = 'pending_source_objects';

    /**
     * EMPTY, like every model in this application. Not one column here is a form field —
     * `storage_key` is generated by `App\Support\Kb\ObjectKey`, and a client-settable one would
     * turn the sweep into a delete-any-object primitive whose argument came from a request body.
     *
     * @var list<string>
     */
    protected $fillable = [];

    public function organizationId(): string
    {
        return $this->organization_id;
    }

    /**
     * @return BelongsTo<Organization, $this>
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }
}
